name: test_api
description: A server app using the shelf package and Docker.
version: 1.0.1
# homepage: https://www.example.com

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  args: ^2.3.1
  firebase_auth_rest: ^2.0.3
  shelf: ^1.4.0
  shelf_router: ^1.1.3
  firebase_auth_token: ^1.0.5
  mongo_dart: ^0.8.2
  intl: ^0.18.0
  firebase_admin_sdk: ^0.0.2

    
  


dev_dependencies:
  http: ^0.13.5
  lints: ^2.0.1
  
  

